# Aligned with .github/workflows/integration-tests.yml@0c69ffa
skipMetricsService: false
containerRuntimeType: containerd

graylog:
  install: true
  host: http://graylog.demo.qubership.org
  initContainerDockerImage: alpine:3.17.2
  elasticsearchHost: http://admin:admin@opensearch.opensearch:9200
  indexShards: 1
  indexReplicas: 0

cloudEventsReader:
  dockerImage: ghcr.io/netcracker/qubership-kube-events-reader:main

fluentbit:
  install: true
  configmapReload:
    dockerImage: ghcr.io/jimmidyson/configmap-reload:v0.13.1
  graylogHost: graylog-service
  graylogPort: 12201

fluentd:
  install: false
