{{- if .Values.fluentbit.install }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-fluentbit-alerts
  labels:
    {{- include "logging.labels" (dict "ctx" . "name" "prometheus-fluentbit-alerts" "component" "monitoring") | nindent 4 }}
    app.kubernetes.io/processed-by-operator: prometheus-operator
    role: alert-rules
    {{- if .Values.fluentbit.labels }}
    {{- include "logging.extraLabels" (dict "ctx" . "extraLabels" .Values.fluentbit.labels) | nindent 4 }}
    {{- end }}
  {{- if .Values.fluentbit.annotations }}
  annotations:
    {{- toYaml .Values.fluentbit.annotations | nindent 4 }}
  {{- end }}
spec:
  groups:
  - name: {{ .Release.Namespace }}-{{ .Release.Name }}
    rules:
    - alert: FluentBit pod is down
      expr: up{job=~".*fluentbit-all-pods"} == 0
      for: {{ .Values.fluentbit.prometheusRules.alertDelay | default "3m" }}
      labels:
        severity: critical
        namespace: {{ .Release.Namespace }}
        service: {{ .Release.Name }}
      annotations:
        summary: "FluentBit pod is down"
        description: "up metric for fluentbit-all-pods = 0 more than {{ .Values.fluentbit.prometheusRules.alertDelay | default "3m" }}."
    - alert: Graylog pod not running
      expr: kube_pod_status_phase{pod=~".*graylog.*", phase!="Running"} == 1
      for: {{ .Values.fluentbit.prometheusRules.alertDelay | default "3m" }}
      labels:
        severity: critical
        namespace: {{ .Release.Namespace }}
        service: {{ .Release.Name }}
      annotations:
        summary: "Graylog pod is not running"
        description: "Graylog pod is not in Running state for more than {{ .Values.fluentbit.prometheusRules.alertDelay | default "3m" }}."
    - alert: Fluent bit high parse error rate
      expr: max by(namespace, pod, container) (rate(fluentbit_parse_error_total[5m])) > {{ default 20 .Values.fluentbit.prometheusRules.parseErrorRateThreshold }}
      for: {{ .Values.fluentbit.prometheusRules.alertDelay | default "5m" }}
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
        service: {{ .Release.Name }}
      annotations:
        summary: "High parse error rate in Fluent Bit"
        description: "Parse error rate is above {{ .Values.fluentbit.prometheusRules.parseErrorRateThreshold | default 20 }} per {{ .Values.fluentbit.prometheusRules.alertDelay | default "5m" }} minutes."
    - alert: Fluentbit high drop records rate
      expr: max by(name) (rate(fluentbit_filter_drop_records_total[5m])) > {{ default 100 .Values.fluentbit.prometheusRules.dropRecordsRateThreshold }}
      for: {{ .Values.fluentbit.prometheusRules.alertDelay | default "5m" }}
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
        service: {{ .Release.Name }}
      annotations:
        summary: "High drop records rate in Fluent Bit"
        description: "Drop records rate is above {{ .Values.fluentbit.prometheusRules.dropRecordsRateThreshold | default 100 }} per {{ .Values.fluentbit.prometheusRules.alertDelay | default "5m" }} minutes."
    - alert: Fluentbit storage overlimit
      expr: increase(fluentbit_input_storage_overlimit[5m]) > 0
      for: {{ .Values.fluentbit.prometheusRules.alertDelay | default "1m" }}
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
        service: {{ .Release.Name }}
      annotations:
        summary: "Fluent Bit storage overlimit"
        description: "Fluent Bit storage overlimit events detected in the last {{ .Values.fluentbit.prometheusRules.alertDelay | default "1m" }}."
    - alert: Fluentbit output retries
      expr: rate(fluentbit_output_retries_total[3m]) > 0
      for: {{ .Values.fluentbit.prometheusRules.alertDelay | default "1m" }}
      labels:
        severity: warning
        namespace: {{ .Release.Namespace }}
        service: {{ .Release.Name }}
      annotations:
        summary: "Fluent Bit output retries detected"
        description: "Rate of fluentbit_output_retries_total is above 0 for the last 3 minutes. This means Fluent Bit is retrying output delivery."
{{- end }}
