{{- if .Values.fluentd.install }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    {{- include "logging.labels" (dict "ctx" . "name" "fluentd-pod-monitor" "component" "monitoring") | nindent 4 }}
    app.kubernetes.io/processed-by-operator: prometheus-operator
    {{- if .Values.fluentd.labels }}
    {{- include "logging.extraLabels" (dict "ctx" . "extraLabels" .Values.fluentd.labels) | nindent 4 }}
    {{- end }}
  {{- if .Values.fluentd.annotations }}
  annotations:
    {{- toYaml .Values.fluentd.annotations | nindent 4 }}
  {{- end }}
  name: fluentd-pod-monitor
spec:
  jobLabel: k8s-app
  podMetricsEndpoints:
    - interval: {{ .Values.fluentd.podMonitor.scrapeInterval }}
      scrapeTimeout: {{ .Values.fluentd.podMonitor.scrapeTimeout }}
      path: /metrics
      # As fluentd worker increment port for sources with increments worker index
      # (port 24231 -> worker 1 -> port 24232)
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: logging-fluentd
{{- end }}
